name: Build

on: [push]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest] # TODO once gfx is working on them again, macos-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
      uses: actions/upload-artifact@v1.0.0
    - name: prepare
      run: |
        mkdir -p build
        cd build
        cmake ..
    - name: build
      run: |
        cd build
        cmake --build . --config Release -j 8
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: out_bin
        path: build/out_bin
